INCIDENTS = [
    {
        "id": "INC-101",
        "type": "fire",
        "severity": 9,
        "people_affected": 180,
        "latitude": 12.9352,
        "longitude": 77.6245,
        "area_name": "Koramangala 5th Block",
        "description": "Commercial kitchen fire spreading to adjacent mixed-use building.",
        "reported_at": "10:42 IST",
    },
    {
        "id": "INC-102",
        "type": "flood",
        "severity": 7,
        "people_affected": 260,
        "latitude": 12.9756,
        "longitude": 77.6066,
        "area_name": "MG Road",
        "description": "Intense waterlogging near metro exits with stranded commuters.",
        "reported_at": "10:49 IST",
    },
    {
        "id": "INC-103",
        "type": "medical",
        "severity": 8,
        "people_affected": 32,
        "latitude": 12.9698,
        "longitude": 77.7500,
        "area_name": "Whitefield",
        "description": "Multiple injuries after traffic collision near ITPL approach road.",
        "reported_at": "10:55 IST",
    },
    {
        "id": "INC-104",
        "type": "collapse",
        "severity": 10,
        "people_affected": 95,
        "latitude": 12.8458,
        "longitude": 77.6603,
        "area_name": "Electronic City Phase 1",
        "description": "Partial building collapse at construction site; trapped workers suspected.",
        "reported_at": "11:02 IST",
    },
]

RESOURCES = [
    {
        "id": "RES-F01",
        "type": "fire_truck",
        "status": "available",
        "latitude": 12.9784,
        "longitude": 77.6408,
        "base_name": "Indiranagar Fire Station",
        "capacity": "high-rise fire response",
    },
    {
        "id": "RES-F02",
        "type": "fire_truck",
        "status": "available",
        "latitude": 12.9250,
        "longitude": 77.5938,
        "base_name": "Jayanagar Fire Station",
        "capacity": "urban fire response",
    },
    {
        "id": "RES-A01",
        "type": "ambulance",
        "status": "available",
        "latitude": 12.9635,
        "longitude": 77.5739,
        "base_name": "Victoria Hospital",
        "capacity": "trauma support",
    },
    {
        "id": "RES-A02",
        "type": "ambulance",
        "status": "available",
        "latitude": 12.9695,
        "longitude": 77.7499,
        "base_name": "Vydehi Hospital Whitefield",
        "capacity": "rapid medical transport",
    },
    {
        "id": "RES-R01",
        "type": "rescue_team",
        "status": "available",
        "latitude": 13.1007,
        "longitude": 77.5963,
        "base_name": "Yelahanka NDRF Staging",
        "capacity": "flood and evacuation support",
    },
    {
        "id": "RES-R02",
        "type": "rescue_team",
        "status": "available",
        "latitude": 12.9121,
        "longitude": 77.6446,
        "base_name": "HSR Layout Rescue Unit",
        "capacity": "collapse search and rescue",
    },
]
